'use strict';

// A reviewable, separate route. The live homepage generator stays unchanged.
const { stripHTML } = require('hexo-util');
const esc = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

hexo.extend.generator.register('archive-home-preview', function (locals) {
  const root = this.config.root;
  const url = path => root + path.replace(/^\//, '');
  const assetUrl = path => url(path).split('/').map((part, index) => index === 0 ? part : encodeURIComponent(part)).join('/');
  const posts = locals.posts.sort('date', -1).toArray();
  const icon = (name, cls = '') => `<svg class="icon ${cls}" aria-hidden="true"><use href="${url('images/archive-icons.svg')}#${name}"></use></svg>`;
  const rows = posts.map(post => {
    const categories = post.categories.toArray().map(item => item.name);
    const tags = post.tags.toArray().map(item => item.name);
    const group = categories.includes('Agent') ? 'Agent' : '工具使用';
    const summary = post.description || stripHTML(post.excerpt || post.content).replace(/\s+/g, ' ').slice(0, 108);
    const memory = post.path.includes('agent-memory');
    const topic = memory ? '论文调研' : group === 'Agent' ? '开发实践' : '工具笔记';
    return `<article class="post-row" data-group="${esc(group)}" data-search="${esc([post.title, summary, ...tags].join(' ').toLowerCase())}"><a class="post-link" href="${url(post.path)}"><div class="post-symbol ${memory ? 'mint' : group === 'Agent' ? 'lavender' : 'sand'}">${icon(memory ? 'memory' : group === 'Agent' ? 'layers' : 'tool')}</div><div class="post-copy"><div class="post-meta"><span>${topic}</span><time datetime="${post.date.format('YYYY-MM-DD')}">${post.date.format('YYYY.MM.DD')}</time></div><h3>${esc(post.title)}</h3><p>${esc(summary)}</p><div class="post-tags">${tags.slice(0, 3).map(tag => `<span># ${esc(tag)}</span>`).join('')}</div></div><span class="row-arrow" aria-hidden="true">↗</span></a></article>`;
  }).join('');
  const data = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>知识存档 · 首页预览</title><meta name="description" content="把探索留下来。AI、智能体与工程实践的个人知识档案。"><link rel="icon" type="image/svg+xml" href="${url('images/archive-mark.svg')}"><link rel="stylesheet" href="${url('css/home-preview.css')}"><script defer src="${url('js/spine-webgl.js')}"></script><script defer src="${url('js/pramanix-background.js')}"></script><script defer src="${url('js/home-preview.js')}"></script></head>
  <body><a class="skip" href="#main">跳转到内容</a>
<div class="sky-shell"><div class="pramanix-environment" aria-hidden="true"></div><div class="pramanix-layer" data-pramanix-background data-skel="${assetUrl('models/pramanix/dyn_illust_char_1046_sbell2_ambienceSynesthesia#8.skel')}" data-atlas="${assetUrl('models/pramanix/dyn_illust_char_1046_sbell2_ambienceSynesthesia#8.atlas')}" data-poster="${url('images/pramanix/poster.webp')}" aria-hidden="true"><img class="pramanix-poster" src="${url('images/pramanix/poster.webp')}" alt=""><canvas class="pramanix-canvas"></canvas></div><canvas class="starfield" data-starfield aria-hidden="true"></canvas><div class="hero-shade" aria-hidden="true"></div><header class="topbar"><a class="sky-brand" href="${url('home-preview/')}">知识存档</a><div class="sky-nav"><a href="#collections">知识专题</a><a href="#notes">最近文章</a><span class="preview-label"><span></span>首页预览</span></div></header>
<section class="welcome"><div class="hero-copy"><div class="eyebrow">A PERSONAL ARCHIVE · EST. 2026</div><h1>知识存档，<br><span>也是新的起点。</span></h1><p>记录 AI、智能体与工程实践。<br>把零散的探索，慢慢连接成自己的知识地图。</p><div class="hero-actions"><a class="hero-button primary" href="${url('agent-memory/')}">${icon('memory')}<span>进入 Agent Memory</span></a><a class="hero-button secondary" href="#collections">查看知识目录 <span aria-hidden="true">↓</span></a></div></div></section><a class="sky-scroll" href="#collections"><span>继续探索</span><i aria-hidden="true"></i></a></div>
<div class="workspace"><aside class="sidebar"><a class="identity" href="${url('home-preview/')}"><img src="${url('images/archive-mark.svg')}" width="48" height="48" alt=""><div><strong>知识存档</strong><span>A PERSONAL ARCHIVE</span></div></a><p class="sidebar-intro">把学到的、做过的，<br>和还在想的，留在这里。</p>
<a class="search-shortcut" href="#article-search">${icon('search')}<span>找一篇笔记</span><kbd>/</kbd></a>
<nav class="primary-nav" aria-label="站点导航"><a class="current" aria-current="page" href="${url('home-preview/')}">${icon('home')}<span>首页</span><span class="nav-dot"></span></a><a href="${url('archives/')}">${icon('archive')}<span>文章归档</span><small>${posts.length}</small></a><a href="#collections">${icon('book')}<span>知识专题</span><small>02</small></a><a href="${url('about/')}">${icon('user')}<span>关于这里</span></a></nav>
<div class="side-label">正在探索</div><nav class="topic-nav" aria-label="专题导航"><a href="${url('agent-memory/')}"><span class="topic-dot teal"></span>Agent Memory${icon('arrow')}</a><a href="${url('categories/Agent/')}"><span class="topic-dot purple"></span>Agent 开发框架${icon('arrow')}</a></nav>
<div class="sidebar-bottom"><div class="small-note">${icon('sprout')}<span>知识在积累，想法在生长。</span></div><a href="https://github.com/lbexplorer/technological_blog">${icon('github')}<span>GitHub</span>${icon('arrow')}</a><span class="copyright">© ${new Date().getFullYear()} 知识存档</span></div></aside>
<div class="main-column"><main id="main" tabindex="-1"><section id="collections" class="collections"><div class="section-title"><h2>${icon('book')}从一个专题开始</h2><span>串起知识，而不止收集文章</span></div><div class="feature-grid">
<a class="memory-feature" href="${url('agent-memory/')}"><div class="feature-top"><span class="label"><span></span>精选专题</span><span class="feature-arrow">↗</span></div><div class="memory-visual" aria-hidden="true"><div class="orbit orbit-1"></div><div class="orbit orbit-2"></div><div class="visual-core">${icon('memory')}</div><span class="visual-chip chip-1">经历</span><span class="visual-chip chip-2">关联</span><span class="visual-chip chip-3">反思</span><i class="satellite sat-1"></i><i class="satellite sat-2"></i></div><div class="feature-copy"><span class="feature-kicker">RESEARCH NOTES / 01</span><h3>Agent Memory</h3><p>让过去的经历，<br>参与下一次思考。</p><div class="feature-bottom"><span>概念 · 论文 · 工程实践</span><strong>进入专题 →</strong></div></div></a>
<a class="framework-feature" href="${url('categories/Agent/')}"><div class="feature-top"><span class="label">实践笔记</span><span class="feature-arrow">↗</span></div><div class="stack-art" aria-hidden="true"><div></div><div></div><div>${icon('layers')}</div></div><div class="feature-copy"><span class="feature-kicker">BUILD & LEARN / 02</span><h3>从框架到实践</h3><p>理解 Agent 如何协作，<br>也记录亲手实现的过程。</p><div class="framework-tags"><span>AutoGen</span><span>AgentScope</span></div></div></a>
</div></section>
<section id="notes" class="notes"><div class="section-title"><h2>${icon('pen')}最近存档</h2><a href="${url('archives/')}">全部文章 ${icon('arrow')}</a></div><div class="filter-bar"><div class="filters" role="group" aria-label="文章分类"><button type="button" data-filter="all" aria-pressed="true">全部 <small>${posts.length}</small></button><button type="button" data-filter="Agent" aria-pressed="false">Agent</button><button type="button" data-filter="工具使用" aria-pressed="false">工具使用</button></div><label class="search-input">${icon('search')}<input id="article-search" type="search" placeholder="搜索标题、摘要或标签" aria-label="搜索标题、摘要或标签"></label></div><div class="post-list">${rows}</div><p class="empty" hidden>没有找到相关笔记，换一个关键词试试。</p><p id="filter-status" role="status" class="filter-status">${posts.length} 篇记录，每一篇都是一次探索。</p></section>
<footer class="main-footer"><span>记录是为了更好地理解。</span><a href="${url('about/')}">关于「知识存档」 ↗</a></footer></main></div></div></body></html>`;
  return { path: 'home-preview/index.html', data };
});
